name: cpp-multichecker

on: [pull_request]
jobs:
  cpp-multichecker:
    name: cpp-multichecker
    runs-on: ubuntu-latest
    steps:
      - name: C++ code check using clang/cppcheck/flawfinder
        uses: naubry/cpp-clang-check@v0.1
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
